# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoChat', '0002_auto_20160216_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationLeader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationFollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
