# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoChat', '0004_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='PublicKey',
        ),
        migrations.RenameField(
            model_name='publickey',
            old_name='public_key',
            new_name='key',
        ),
    ]
