# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoChat', '0005_auto_20160305_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicKeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
