# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoChat', '0007_auto_20160305_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
